server:
    port: 8081
    servlet:
        context-path: /movement-service
spring:
    application:
        name: movement-service
    datasource:
        url: jdbc:postgresql://db-prueba-devsu:5432/devsu_db
        username: devsu_user
        password: devsuPass2@2S
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
    bootstrap-servers: kafka:9092
    group:
        id: devsu-kafka-group
    topic:
        client: devsu-kafka-topic

logging:
    level:
        root: INFO
        com.devsu.res.movement_service.adapter.inbound.controller: DEBUG 
        com.devsu.res.movement_service.adapter.inbound.aop: DEBUG 

api:
    rest:
        customer-service:
            url: http://customer-service:8080/customer-service
            client-path: /clientes/{id}